name: vc
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - flake8
  - ipywidgets
  - isort
  - jupyterlab
  - lxml
  - matplotlib
  - mypy
  - nodejs
  - pandarallel
  - pipenv
  - plotly
  - python
  - scikit-learn
  - seaborn
  - textblob
  - xgboost
